### ISSUE TITLE
After incorrect guess, next game shows definition of wrong word

### ISSUE THREAD

**Issue by joshtriplett** [sigvef/fiveletters.xyz#1]
Thanks for the great game!

I noticed an issue after the addition of definitions:

After making an incorrect final guess, the next game uses the correct word as the initial guess, but shows the definition of the incorrect guess.

![Screenshot_20220109-235950](https://user-images.githubusercontent.com/162737/148734439-6579e3bf-69a7-43c8-a933-b389e9b42f22.png)

**Comment by sigvef** [comment]
Thanks for the report! The issue should be fixed now.

**Comment by joshtriplett** [comment]
@sigvef Thank you!
